name: Simple Hello World Workflow

on:
  push:
    branches:
      - uat

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Run a simple script
        run: |
          echo "Hello, GitHub Actions!"
          echo "This workflow is running on a push event to the main branch."